#!/bin/bash
if [ -z "$BASH_VERSION" ];then
	echo "It appears you are using dash or sh, you must use bash or rbash to run this script"
	exit
fi
here=$(dirname $0)
echo "Need a couple dependencies"
sudo apt-get install -m curl php5-cli libnotify-bin
if [[ ! -f /usr/bin/curl || ! -f /usr/bin/php5 || ! -f /usr/bin/notify-send ]];then
	echo "You did not install the dependencies"
	echo "You need have the curl, php5, and notify-send commands available for use"
	exit
fi
mkdir -p ~/.config/autostart/
cp $here/*.desktop ~/.config/autostart/
chmod +x $here/KernelUpdate*
sudo cp $here/KernelUpdate* /usr/local/bin/
echo -e "Install Complete\nUpdates will be checked for 60 seconds after login\nIf you want Release Candidates you will need to edit the new startup entry."
