#!/bin/bash
if [ "$1" == "-h" ] || [ "$1" == "--help" ];then
	echo "This script sends data to KernelUpdateScriptGenerator"
	echo "This script saves the update script made by the script to a file and gives the user instructions"
	echo "This is the help info from KernelUpdateScriptGenerator"
	KernelUpdateScriptGenerator $1
else
	KernelUpdateScriptGenerator "$1" "$2" "$3" "$4" "$5" "$6" "$7" "$8" > /tmp/kernel-update
	chmod +x /tmp/kernel-update
	if [ $(cat /tmp/kernel-update | wc -l) -gt 10 ];then
		notify-send --icon=info -t 10000 "To Upgrade" "Run this in a terminal:\n/tmp/kernel-update"
		echo -e "Run this command to install the new kernel\n\t/tmp/kernel-update"
	fi
fi
