#!/usr/bin/php
<?php
// This is a client side php script, as such it needs the php5-cli package to work
// This script generates a bash script
$NO_RC=false;
$version=false;
$r=false;
foreach($argv as $key => $val){
  if($val=='-no-rc')
		$NO_RC=true;
	else if($val=='-v'){
		if(!isset($argv[$key+1]))
			break;
		$version=$argv[$key+1];
		if(!is_numeric(substr($version,0,1)))
			die("$version is not a version number\n");
	}
	else if($val=='-r'){
		if(!isset($argv[$key+1]))
			break;
		$r=$argv[$key+1];
	}
	else if($val=='-h'||$val=='--help'){
		$script=strrpos($_SERVER["SCRIPT_NAME"],'/');
		if(!is_bool($script))
			$script=substr($_SERVER["SCRIPT_NAME"],$script+1);
		else
			$script=$_SERVER["SCRIPT_NAME"];
		echo "Options:\n\t-no-rc sets the script to ignore Release Canidate versions\n";
		echo "\t-r overrides the release version\n\t\teg: `".$script." -r raring` \n\t\tWould mean to a only kernels for raring even if you are using quantal\n";
		echo "\t-v is used to specify version series\n\t\teg: `".$script." -v 3.8` \n\t\tWould mean to a only accept kernels starting with 3.8 in the version number";
		die("\n");
	}
}
if(is_bool($r))
	$r=substr(shell_exec('lsb_release -sc'),0,-1);
$k=shell_exec("uname -r");
echo "#!/bin/bash\n\n";
echo "# Config Notes:\n";
echo "# \t".(!$NO_RC?"Accept":"Ignore")." Release Canidates\n";
echo "# \tAccept Latest".(is_bool($version)?'':' '.$version)." Kernel\n";
echo "# \tAccepting kernels compiled for $r\n";
echo "# \tAccepting kernels with a version higher than $k\n";
$url="http://kernel.ubuntu.com/~kernel-ppa/mainline/";
$html=file_get_contents($url);
$DOM=new DOMDocument;
$DOM->loadHTML($html);
$links=$DOM->getElementsByTagName('a');
$arr=array();
$arr2=array();
$k=explode('-',$k);
$dir='';
for ($i = 0; $i < $links->length; $i++){
	$name=substr($links->item($i)->nodeValue,1,-1);
	if(strpos($name,$r)>0){
		if(($NO_RC && strpos($name,'-rc')>0)||(!is_bool($version) && substr($name,0,strlen($version))!=$version))
			continue;
		$name2=substr($name,0,strpos($name,"-$r"));
		if(version_compare($name,$k[0])==1){
			$k[0]=$name2;
			array_push($arr,$name2);
			array_push($arr2,'v'.$name.'/');
		}
	}
}
if(count($arr)>0){
	$k=$arr[count($arr)-1];
	shell_exec("notify-send 'Update Available' 'Kernel $k is available.'");
	$url=substr($url.$arr2[count($arr2)-1],0,-1);
	$html=file_get_contents($url);
	$DOM=new DOMDocument;
	$DOM->loadHTML($html);
	$links=$DOM->getElementsByTagName('a');
	for ($i = 0; $i < $links->length; $i++){
		$name=$links->item($i)->nodeValue;
		if(strpos($name,'.deb')>0)
			break;
	}
	$name=substr($name,strpos($name,'_')+1,-1*strlen(substr($name,strrpos($name,'_'))));
	$a=substr($name,0,strrpos($name,'.'));
	$b=substr($name,strrpos($name,'.')+1);
}
else
	die("exit\n");
echo "WHERE=\"$url\"\n";
echo "VER_A=\"$a\"\n";
echo "VER_B=\"$b\"\n";
?>

if [ "$1" == "--uninstall" ];then
	sudo apt-get purge linux-{image-extra,headers,image}-$VER_A-generic linux-headers-$VER_A
	exit
fi

LOC="/tmp/kernel-$VER_A"
if [ -d "$LOC" ];then
	clear
	echo -e "Warning: This script has been run already\nFiles are in $LOC\nDelete existing downloads? (y=Yes, n=No) (y)"
	read action
	if [ ! "$action" == "n" ];then
		rm $LOC/*
	fi
else
	mkdir $LOC
fi
cd $LOC
if [ "`uname -m`" == "x86_64" ];then
	arch="amd64"
else
	arch="i386"
fi
echo "Kernel Version $VER_A"
echo "Care to look at the change log? (y=Yes, n=No) (n)"
read action
if [ "$action" == "y" ];then
	curl $WHERE/CHANGES 2> /dev/null | less
	echo -e "Now that you read the change log, do you want to upgrade (y=Yes, n=No) (y)"
	read action
	if [ "$action" == "n" ];then
		exit
	fi
fi
wget -nc $WHERE/linux-headers-$VER_A"_$VER_A"."$VER_B"_all.deb
wget -nc $WHERE/linux-{image-extra,headers,image}-$VER_A-generic_$VER_A."$VER_B"_$arch.deb
clear
if [ `ls linux-*.deb | wc -l` -ne 4 ];then
	echo -e "Failed to download all needed files\nFiles are in $LOC\nGet files from $WHERE\n\nThere should be 4 files, 3 ending with '$arch.deb' and 1 with 'all.deb'\nHere is what we have:"
	ls $LOC
	echo -e "\nYou can install what you have by running this command:\n\tsudo dpkg -i $LOC/linux-*.deb\nJust be prepared for broken packages."
	exit
fi
sudo dpkg -i ./linux-*.deb
echo -e "\n\nAre you ready to Reboot? (y=Yes, n=No) (n)"
read action
if [ "$action" == "y" ];then
	sudo reboot
fi
exit
